### ISSUE TITLE
New role system doesn't remove old role

### ISSUE THREAD

**Issue by falcuma** [PlayQ4/issues#1]
New role system is preventing people from removing themselves of the old roles, getting notified for a queue when they don't have the role anymore.

**Comment by 0xDECAFFED** [comment]
My Roles settings were like this:
![Screenshot 2023-10-09 183533](https://github.com/PlayQ4/issues/assets/5190590/de04505d-0d7d-40bc-9012-1c646c704f84)
but I was still getting notified for Duel or TDM queues.

After manual role removal by a mod I can add & delete any roles successfully via the questionnaire.
Notifications work as expected afterwards.

**Comment by GelbEinhalb** [comment]
Thank You!
I will think of some solution for that :D

**Comment by GelbEinhalb** [comment]
This will get fixed with the rewrite of the [queue system](https://discord.com/channels/834908433073045604/1133119749983846440)

I will add something like notification settings but I'm not sure yet on how exactly I'm going to do that.

**Comment by GelbEinhalb** [comment]
Discord seems to have fixed this before I could.

You can now remove existing roles by just clicking the corresponding [button](https://discord.com/channels/834908433073045604/customize-community) to "add" the role to your account and then clicking button again to remove it.

This will remove any previous role that has not been added by the Discord "customize-community" feature.

Let me know if this has some kind of exception 😄
